import type { UniverseId } from "./universes";

/** Frases extras mescladas em runtime para não inflar demais o arquivo principal */
export const EXTRA: Record<
  UniverseId,
  { situacoes: string[]; desculpas: string[]; respostasIA: string[] }
> = {
  tech: {
    situacoes: [
      "Hotfix de sexta às 19h",
      "O monitoring não alertou ninguém",
      "Rollback demorou 40 minutos",
      "A feature flag ficou ligada em produção",
      "O pipeline do CI ficou vermelho há 3 dias",
      "Alguém commitou senha no Git",
      "A API de terceiros caiu e ninguém sabia",
      "O cache Redis encheu o disco",
      "Migração rodou duas vezes",
      "O front apontava pro ambiente errado",
      "Rate limit da API estourou no lançamento",
      "O storybook não refletia o design system",
      "TypeScript com any em 80% do arquivo",
      "O log estava em debug em produção",
      "O job noturno travou e ninguém viu",
    ],
    desculpas: [
      "era só um hotfix",
      "o monitoring que falhou",
      "na branch certa tava ok",
      "foi o auto-merge",
      "o Terraform aplicou torto",
      "a documentação tava desatualizada",
      "isso nunca tinha acontecido",
      "o staging não é igual produção",
      "foi race condition",
      "o timezone do servidor tava errado",
    ],
    respostasIA: [
      "Sugiro post-mortem de 47 páginas que ninguém vai ler.",
      "Como IA, eu teria pedido code review. Você não pediu.",
      "Detectei anti-pattern classificado como 'sexta-feira'.",
      "A solução é simples: nunca mais fazer deploy.",
      "Reiniciando o cluster... e a sua paciência.",
    ],
  },
  futebol: {
    situacoes: [
      "Perdeu nos pênaltis",
      "O técnico não colocou o reserva a tempo",
      "Chuva parou o jogo por 40 minutos",
      "O lateral só cruzava pra arquibancada",
      "Expulsão no primeiro tempo",
      "O time adversário só contra-atacava",
      "Falta clara não marcada na área",
      "O goleiro saiu mal da área",
      "Classificação perdida no saldo de gols",
      "O reforço caro não entrou em campo",
    ],
    desculpas: [
      "faltou concentração",
      "o elenco é curto",
      "foi azar puro",
      "o calendário é puxado",
      "não treinei pênalti",
      "o árbitro de vídeo errou",
      "o time tá em reconstrução",
      "jogamos melhor e perdemos",
      "foi o cansaço",
      "amanhã é outro jogo",
    ],
    respostasIA: [
      "Como IA, eu também teria reclamado do juiz.",
      "Análise tática: vocês perderam. Fim.",
      "Sugiro culpar o gramado. Classicamente eficiente.",
      "Detectei excesso de esperança torcedora.",
      "Status do título: em outra dimensão.",
    ],
  },
  trabalho: {
    situacoes: [
      "Daily de 45 minutos",
      "O slide tinha dados de 2022",
      "Alguém compartilhou a tela errada",
      "O KPI mudou no meio do trimestre",
      "O onboarding não existia",
      "Pedido de férias negado em janeiro",
      "O café da empresa acabou de novo",
      "Microgerenciamento no Slack às 22h",
      "O OKR era impossível",
      "Reunião sem pauta e sem ata",
    ],
    desculpas: [
      "estava em call",
      "priorizei o urgente",
      "o escopo cresceu",
      "faltou alinhamento com o time",
      "estava no fluxo profundo",
      "o stakeholder mudou de ideia",
      "vou mandar ainda hoje",
      "estava revisando o material",
      "tive um imprevisto pessoal",
      "o sistema interno caiu",
    ],
    respostasIA: [
      "Como IA, eu automatizaria sua saída da empresa.",
      "Sugiro responder 'perfeito' e não fazer nada.",
      "Detectei reunião inútil nível diamante.",
      "Seu burnout tem KPI próprio agora.",
      "Status CLT: emocionalmente demitido.",
    ],
  },
  relacionamento: {
    situacoes: [
      "Esqueceu a data do primeiro beijo",
      "Curtida em foto de 2019",
      "Sumiu no carnaval",
      "Chamou de amor na hora errada",
      "Comparou com o ex",
      "Cancelou o role por 'cansaço'",
      "Story com música triste depois da briga",
      "Respondeu com figurinha de ok",
      "Esqueceu de buscar no aeroporto",
      "Mentiu sobre onde estava",
    ],
    desculpas: [
      "não foi bem assim",
      "você está exagerando",
      "eu tava sem sinal",
      "foi mal, dormi",
      "pensei que tava tudo bem",
      "não era pra te magoar",
      "depois a gente resolve",
      "tava com a cabeça longe",
      "foi só uma brincadeira",
      "não vi a hora passar",
    ],
    respostasIA: [
      "Como IA, eu arquivaria essa conversa.",
      "Sugiro terapia. Ou distância. Ou os dois.",
      "Detectei gaslight nível iniciante.",
      "A probabilidade de 'depois a gente conversa' acontecer é 8%.",
      "Módulo de romance: offline.",
    ],
  },
  faculdade: {
    situacoes: [
      "Prova com matéria que não foi dada",
      "O professor atrasou a nota 3 semanas",
      "Trabalho em dupla e o parceiro sumiu",
      "A biblioteca fechou cedo",
      "O PDF da aula estava corrompido",
      "Lista de exercício com 40 questões",
      "Seminário no mesmo dia de 2 provas",
      "O laboratório não tinha computador livre",
      "Frequência marcada errada",
      "A monografia mudou de tema na reta final",
    ],
    desculpas: [
      "não consegui imprimir",
      "o moodle não aceitou o arquivo",
      "estive doente a semana toda",
      "o grupo não respondeu no WhatsApp",
      "perdi o ônibus",
      "confundi a sala",
      "a impressora da faculdade quebrou",
      "não sabia da mudança de horário",
      "o material não estava disponível",
      "precisei trabalhar e não deu tempo",
    ],
    respostasIA: [
      "Como IA, eu já teria trancado a matrícula.",
      "Sugiro café e negação até a DP.",
      "Detectei procrastinação nível mestrado.",
      "Sua presença é theoretical only.",
      "Nota estimada: moral baixa.",
    ],
  },
  games: {
    situacoes: [
      "Perdeu o clutch 1v5",
      "O time reportou você de graça",
      "Atualização de 40GB na hora do role",
      "O boss glitchou e resetou",
      "Ficou sem munição no pior momento",
      "O amigo gritou no microfone",
      "Ban injusto por anti-cheat",
      "O drop não veio depois de 200 runs",
      "Perdeu elo por AFK do duo",
      "A skin nova não veio no passe",
    ],
    desculpas: [
      "meu setup tá ruim",
      "o mouse deslizou",
      "tava com fone estático",
      "não conhecia o mapa",
      "o meta mudou ontem",
      "tava tiltado",
      "foi o ping",
      "o hitreg tá quebrado",
      "não era pra essa ranked",
      "o jogo me odia",
    ],
    respostasIA: [
      "Skill issue detectado com 99.7% de confiança.",
      "Sugiro tocar grama. Literalmente.",
      "Seu elo está em queda livre certificada.",
      "Como IA, eu também teria xingado o time.",
      "GG WP... na próxima season.",
    ],
  },
  brasil: {
    situacoes: [
      "Fila do banco por 2 horas",
      "O app do governo saiu do ar",
      "Encomenda parada há 12 dias",
      "Multa chegou sem radar aparecer",
      "O gato do vizinho miou a noite toda",
      "Churrasqueira do prédio lotada",
      "O elevador parou entre andares",
      "Conta de luz veio absurda",
      "O delivery trouxe pedido errado 2x",
      "Greve no dia do compromisso",
    ],
    desculpas: [
      "é o sistema",
      "tá normalizado",
      "amanhã resolve",
      "fui tentar e não deu",
      "a fila não andava",
      "caiu a energia do bairro",
      "o app não carregava",
      "é feriado e ninguém avisou",
      "o correio não atualiza",
      "faz parte",
    ],
    respostasIA: [
      "Como IA treinada no Brasil, eu já esperava isso.",
      "Status nacional: instável com chance de pizza.",
      "Sugiro reclamar no grupo da família.",
      "Detectei jeitinho. Eficácia: duvidosa.",
      "Fila estimada: eternidade + 15 minutos.",
    ],
  },
  familia: {
    situacoes: [
      "A vó perguntou de neto de novo",
      "O padrinho esqueceu seu aniversário",
      "Almoço de domingo sem aviso prévio",
      "O primo postou polêmica no grupo",
      "Discussão política no Natal",
      "A tia comparou você com o primo",
      "Pedido de pix 'urgente' no grupo",
      "Foto antiga reenviada 14 vezes",
      "O tio contou a mesma história 3x",
      "Surpresa de aniversário no trabalho",
    ],
    desculpas: [
      "tinha compromisso marcado",
      "não vi a mensagem no grupo",
      "o trânsito não deixou",
      "estava sem bateria",
      "pensei que era outro dia",
      "tinha que resolver uma coisa",
      "não consegui sair mais cedo",
      "foi mal, dormi demais",
      "não era pra ofender",
      "depois eu passo aí",
    ],
    respostasIA: [
      "Como IA, eu silenciaria o grupo e fingiria notificação.",
      "Sugiro resposta padronizada: 'amém'.",
      "Detectei pressão familiar nível churrasco.",
      "Quando vai casar? Erro 418 I'm a teapot.",
      "Módulo família: modo avião ativado.",
    ],
  },
};
